/*
 * @Date: 2024-01-13 15:09:05
 * @Author: Bruce Hsu
 * @Description: 
 */

// src/app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// Custom Imports
import { AuthProvider } from '@/auth/context'
import { AuthConsumer } from '@/auth/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
				<AuthProvider>
					<AuthConsumer>{children}</AuthConsumer>
				</AuthProvider>
			</body>
    </html>
  )
}
